export const HotelData = [
	{
		id: 1,
		name: "The Verda Driftwood",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1509531805/Hotel/00096502/Executive_Room_4kPV3N.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1524035470/Hotel/Leh/00096502/Facade-1_Bvu22H.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1505128885/Hotel/Leh/00096502/Hotel_External_Picture_mQ10FR.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1505128918/Hotel/Leh/00096502/Dontha_Restaurant_1_5j4KUl.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1505129056/Hotel/Leh/00096502/Dontha_Restaurant_vyuVrH.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1505129070/Hotel/Leh/00096502/Hotel_Corridor_GHVM8s.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1509531603/Hotel/00096502/Deluxe_Room_h48jTO.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1509531655/Hotel/00096502/Deluxe_Room1_dfRJT3.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1509531839/Hotel/00096502/Executive_Room_1_cVsaDz.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1509531871/Hotel/00096502/exterior_view_11(1)_bqbW9b.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1509531889/Hotel/00096502/Privilege_Suite_Pj04ju.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1509531920/Hotel/00096502/Privilege_Suite1_UWwp5T.jpg",
		],
		rating: 4.5,
		price: 6999,
		sPrice: "6,999",
		otherRatingName: "Spectacular  Location",
		otherRating: 5.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: [" Spectacular Location", "Exemplary Cleanliness"],
		ratingArray: ["5.0/5", "5.0/5"],
		overView:
			"The Driftwood Ladakh is a premium resort located at a distance of 13 km from Leh Palace and 15 km from Shanti Stupa. This hotel in Leh offers free Wi-Fi access to its guests.It comprises of 32 spacious and well-kept suites, spread over 3 floors. Some of the amenities offered with the rooms include wardrobe, television, separate sitting area, balcony and attached bathroom with hot and cold running water facility.The Driftwood Ladakh has garden dining area, travel desk, restaurant and front desk facility.The Leh hotel can be reached via Bus Stand LBOC Ltd Leh (11 km) and Leh Kushok Bakula Rimpochee Airport (13 km). Some of the tourist attractions are Pangong Tso Lake (213 km), Hall of Fame (14 km) and Shanti Stupa (15 km).Note: Internet connectivity is subject to internet service provide",
		city: "Leh",
		cleanPass: true,
		location: "Village Shey",
		service: 3,
		couple: true,
		feeCancellation: true,
		breakfast: true,
		wifi: true,
		airportTranspotation: true,
		laundry: true,
		bar: true,
		children: true,
		swimmingPool: true,
		parking: true,
		hotles: true,
		resort: false,
		guestHouse: false,
		villa: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: false,
	},
	{
		id: 2,
		name: "Abu Palace",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534804/Hotel/Leh/00147490/IMG-5885_(1)_uvaJYU.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534804/Hotel/Leh/00147490/IMG-5885_(1)_uvaJYU.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534821/Hotel/Leh/00147490/IMG-5891_Lz1xw0.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534832/Hotel/Leh/00147490/bae373c6-3cbb-46cb-bdd7-27d9c65acfef_Duj2Fo.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534851/Hotel/Leh/00147490/e0febfae-4146-4391-8487-610cab48772e_eEzvlv.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534873/Hotel/Leh/00147490/IMG-5274_4LnkP7.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534907/Hotel/Leh/00147490/31424bf2-7ca3-49a6-b5f3-eca9f3a2083d_(1)_P6KEip.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534923/Hotel/Leh/00147490/1b3270ca-3475-4baf-8e9a-ff3c3fd0005a_(1)_ahA4He.jpg",
		],
		rating: 3,
		price: 1760,
		sPrice: "1,760",
		otherRatingName: "Impressive  Location ",
		otherRating: 4.0,
		tripAdvicerRating: 3,
		otherRatingName1: [" Impressive Location ", "Good Service "],
		ratingArray: ["4.0/5", "3.5/5"],
		overView:
			"Guests can enjoy easy access to tourist attractions with stay at Abu Palace hotel. Located close to Kyigu Drak Gonpa, Abu Palace offers complimentary internet access to its patrons.Hotel Facilities 24-hour front desk, luggage storage area, travel counter and garden are a few of the facilities offered at Abu Palace. This hotel in Leh offers room service, airport transfers (surcharge) and medical assistance for the convenience of the guests.Room Facilitie.This property has 24 well-maintained rooms. Television, telephone, room heater, wardrobe and bathroom with hot/water facility are few of the amenities in the rooms.Dining.Guest can dine-in at the restaurant within the premises.Important LandmarksAbu Palace is close to the travel hubs like Bus Stand JK SRTC (1 km) and Kushok Bakula Rimpochee Airport (3 km). Places worth visiting are Leh Palace (1 km) and Shanti Stupa (4 km).What people love the most about this property is its great location and classy ambiance. Book now and enjoy world-class services at Abu Palace.",
		city: "Leh",
		cleanPass: false,
		location: "Old Road",
		service: 0,
		couple: false,
		feeCancellation: false,
		breakfast: false,
		wifi: false,
		airportTranspotation: true,
		laundry: true,
		bar: false,
		children: true,
		swimmingPool: true,
		parking: true,
		hotles: true,
		resort: false,
		villa: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: true,
		welcomeHeritageHotel: false,
	},
	{
		id: 3,
		name: "Hotel Lingzi",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451989068/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/OVER-VIEW.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1452061238/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/Hotel-Terrace-View.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451989349/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/SUPER-DELUXE-ROOM.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451989078/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/TERRACE-1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451988983/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/BEDROOM.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451988986/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/EXECUTIVE-ROOM.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451988983/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/CLASSIC-ROOM.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451989081/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/WASHROOM.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451989071/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/RECEPTION.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451989083/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/WASHROOM-1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1451989055/Domestic%20Hotels/Hotels_Leh/Hotel%20Lingzi/FRONT.jpg",
		],
		rating: 3,
		price: 4180,
		sPrice: "4,180",
		otherRatingName: "Wonderful  Location",
		otherRating: 4.5,
		tripAdvicerRating: 4.5,
		otherRatingName1: [" Impressive Service", " Wonderful Location"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"The Yatra SMART choice property comes with a promise of 8 assured amenities, money-back guarantee and priority helpline support. You also get free cancellation and standardized prices through the year.Established in 1982, Hotel Lingzi is an 'A' class hotel located very centrally in the very heart of the city. Close to various shopping marts, airline office, post office and taxi stand; the hotel offers a 360 degree breathtaking view of the Leh Palace, Namgyal Monastery, Shanti Stupa and the surrounding mountains.The guests are offered Indian, Continental, Chinese, Tibetian and traditional Ladakhi cuisines at the hotel. The hotel also has a terrace garden with an excellent view to appeal to the visual and ascetic senses.",
		city: "Leh",
		cleanPass: false,
		location: "Chulung Old Road",
		service: 1,
		couple: true,
		feeCancellation: false,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: false,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: true,
		hotles: true,
		resort: false,
		villa: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: true,
	},
	{
		id: 4,
		name: "Ladakh Inn",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534804/Hotel/Leh/00147490/IMG-5885_(1)_uvaJYU.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534804/Hotel/Leh/00147490/IMG-5885_(1)_uvaJYU.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534821/Hotel/Leh/00147490/IMG-5891_Lz1xw0.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534832/Hotel/Leh/00147490/bae373c6-3cbb-46cb-bdd7-27d9c65acfef_Duj2Fo.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534851/Hotel/Leh/00147490/e0febfae-4146-4391-8487-610cab48772e_eEzvlv.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534873/Hotel/Leh/00147490/IMG-5274_4LnkP7.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534907/Hotel/Leh/00147490/31424bf2-7ca3-49a6-b5f3-eca9f3a2083d_(1)_P6KEip.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1549534923/Hotel/Leh/00147490/1b3270ca-3475-4baf-8e9a-ff3c3fd0005a_(1)_ahA4He.jpg",
		],
		rating: 3,
		price: 1760,
		sPrice: "1,760",
		otherRatingName: "Astounding  Value",
		otherRating: 5.0,
		tripAdvicerRating: 5,
		otherRatingName1: ["Astounding Value", " Wonderful Location"],
		ratingArray: ["5.0/5", "4.5/5"],
		overView:
			"Situated approximately 2 km from the Leh Palace, Ladakh Inn provides free breakfast and Wi-Fi connectivity to its patrons. The property in Leh is accessible from the Bus Stand JK SRTC, 2 km away.The hotel has 11 well-maintained rooms provided with the required requisites. Few of the conveniences available in the rooms include makeup mirror, reading lamps, bottled drinking water, wardrobe and attached bathroom with a supply of hot/cold running water. This property in Leh offers guests a selection of delicacies at the in-house multi-cuisine restaurant. Dance performances (on request), laundry, doctor on call and travel assistance are a few of the conveniences guests can avail during their stay. There is a garden available on the premises.Ladakh Inn is at a distance of 5 km from the Leh Kushok Bakula Rimpochee Airport. Points of interest nearby include Red Maitreya Temple (1 km) and Gomang Stupa (2 km). ",
		city: "Leh",
		cleanPass: true,
		location: "Chulung Old Road",
		service: 1,
		couple: false,
		feeCancellation: false,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: false,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: true,
		hotles: true,
		villa: false,
		resort: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: true,
	},
	{
		id: 5,
		name: "Hotel Charu Palace",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564396987/Hotel/Leh/00062463/1_zBWZeJ.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564396987/Hotel/Leh/00062463/1_zBWZeJ.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1453672229/Domestic%20Hotels/Hotels_Leh/Hotel%20Charu%20Palace/Suite_Room.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397001/Hotel/Leh/00062463/2_LPiExS.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397007/Hotel/Leh/00062463/3_zvimy4.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397014/Hotel/Leh/00062463/4_uDgeyE.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397021/Hotel/Leh/00062463/5_ZVyzeb.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397028/Hotel/Leh/00062463/6_OmgLf8.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397036/Hotel/Leh/00062463/7_O3fLeE.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397052/Hotel/Leh/00062463/9_dajKjg.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397065/Hotel/Leh/00062463/11_M55n1z.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1564397072/Hotel/Leh/00062463/12_i2MLlg.jpg",
		],
		rating: 3,
		price: 4706,
		sPrice: "4,706",
		otherRatingName: "Wonderful  Location ",
		otherRating: 4.5,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"Offering 24-hour front desk facility, Hotel Charu Palaceis situated at a distance of 3 km from Leh Palace and 7 km from Leh Kushok Bakula Rimpochee Airport.This Leh hotel accommodates 16 furnished rooms. Some of the in-room amenities include tea/coffee maker, bottled drinking water, wake-up calls, wardrobe, television and sofa. The rooms also have an attached bathroom with hot and cold water facility.This hotel in Leh has a restaurant within its premises. Other services like airport transfers (chargeable), laundry, medical and 24-hour room service are available at the hotel. Power backup generator is also available at this property. Hotel Charu Palace has a garden within its premises. Guests can visit the famous tourist spots like Magnetic Hill (30 km), Thikse Gompa (20 km) and Leh Palace (3 km). Leh Old Bus Stand is 3 km away from this property.",
		city: "Leh",
		cleanPass: true,
		location: "Lower Tukcha Road",
		service: 1,
		couple: false,
		feeCancellation: false,
		breakfast: true,
		wifi: false,
		airportTranspotation: true,
		laundry: true,
		bar: true,
		villa: false,
		children: false,
		swimmingPool: false,
		parking: true,
		hotles: true,
		resort: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: false,
	},
	{
		id: 6,
		name: "WelcomHeritage Lha-Ri-Sa Resort",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436317029/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Cottage_3.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436317029/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Cottage_3.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1467521541/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Deluxe%20Room/Deluxe_Room_vvLDIY.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462447811/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Interior.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462447793/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Hotel_Hall.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462448333/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Deluxe_Room.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462448335/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Tree_House_Room_1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462448341/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Deluxe_Room_1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462448331/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Tree_House_Room_2.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462448372/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Exterior.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462447795/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Interior_1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1462447792/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Interior_2.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436317020/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/BedRoom_3.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436317031/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Cottage_2.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436317029/Domestic%20Hotels/Hotels_Leh/WelcomHeritage%20Lha-Ri-Sa%20Resort/Dinning.jpg",
		],
		rating: 3,
		price: 5400,
		sPrice: "5,400",
		otherRatingName: "Wonderful  Location ",
		otherRating: 4.5,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"Offering 24-hour front desk facility, Hotel Charu Palaceis situated at a distance of 3 km from Leh Palace and 7 km from Leh Kushok Bakula Rimpochee Airport.This Leh hotel accommodates 16 furnished rooms. Some of the in-room amenities include tea/coffee maker, bottled drinking water, wake-up calls, wardrobe, television and sofa. The rooms also have an attached bathroom with hot and cold water facility.This hotel in Leh has a restaurant within its premises. Other services like airport transfers (chargeable), laundry, medical and 24-hour room service are available at the hotel. Power backup generator is also available at this property. Hotel Charu Palace has a garden within its premises. Guests can visit the famous tourist spots like Magnetic Hill (30 km), Thikse Gompa (20 km) and Leh Palace (3 km). Leh Old Bus Stand is 3 km away from this property.",
		city: "Leh",
		cleanPass: false,
		location: "Skara",
		service: 2,
		couple: false,
		feeCancellation: true,
		breakfast: true,
		wifi: true,
		airportTranspotation: false,
		laundry: false,
		bar: true,
		children: false,
		swimmingPool: true,
		parking: true,
		hotles: false,
		villa: false,
		resort: true,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: true,
		welcomeHeritageHotel: false,
	},
	{
		id: 7,
		name: "Zambala Inn",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558698258/Hotel/00150198/SAR_2635_TNs0lK.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558698258/Hotel/00150198/SAR_2635_TNs0lK.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558698308/Hotel/00150198/SAR_2624_JGWQrN.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558698383/Hotel/00150198/SAR_2616_H4hsJU.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558698477/Hotel/00150198/SAR_2619_JZXVAK.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558699173/Hotel/00150198/SAR_2668_bhZlW5.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558699189/Hotel/00150198/SAR_2682_(1)_RQNLr5.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558699203/Hotel/00150198/SAR_2694_AaNXGS.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558699222/Hotel/00150198/SAR_2707_NW98gj.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558699251/Hotel/00150198/SAR_2712_yQkcbD.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1558933727/Hotel/Leh/00150198/PANO_20180802_110021_V6cLN4.jpg",
		],
		rating: 3,
		price: 2400,
		sPrice: "2,400",
		otherRatingName: "Wonderful  Location ",
		otherRating: 5.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"Offering 24-hour front desk facility, Hotel Charu Palaceis situated at a distance of 3 km from Leh Palace and 7 km from Leh Kushok Bakula Rimpochee Airport.This Leh hotel accommodates 16 furnished rooms. Some of the in-room amenities include tea/coffee maker, bottled drinking water, wake-up calls, wardrobe, television and sofa. The rooms also have an attached bathroom with hot and cold water facility.This hotel in Leh has a restaurant within its premises. Other services like airport transfers (chargeable), laundry, medical and 24-hour room service are available at the hotel. Power backup generator is also available at this property. Hotel Charu Palace has a garden within its premises. Guests can visit the famous tourist spots like Magnetic Hill (30 km), Thikse Gompa (20 km) and Leh Palace (3 km). Leh Old Bus Stand is 3 km away from this property.",
		city: "Leh",
		cleanPass: true,
		location: "Changspa",
		service: 0,
		couple: false,
		feeCancellation: false,
		breakfast: false,
		wifi: false,
		airportTranspotation: false,
		laundry: false,
		bar: false,
		children: false,
		swimmingPool: false,
		parking: true,
		hotles: true,
		resort: false,
		villa: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: false,
	},
	{
		id: 8,
		name: "Sangto Green Guest House",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002166/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Overview.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002166/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Overview.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1467517573/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Standard%20Room/Standard_Room_hXYoqx.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002199/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Parking.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002212/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Reception_Lobby.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002201/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Entrance.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002209/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Exterior_2.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002265/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Exterior_3.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002196/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Exterior_4.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002177/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Bedroom4.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002176/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Bedroom5.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002161/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Bedroom_1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002156/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Bedroom_2.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1438002160/Domestic%20Hotels/Hotels_Leh/Sangto%20Green%20Guest%20House/Bedroom_3.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1555589755/Hotel/Leh/00045081/1_lChysO.jpg",
		],
		rating: 1,
		price: 2400,
		sPrice: "2,400",
		otherRatingName: "Wonderful  Location ",
		otherRating: 4.5,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"Sangto Green Guest has a landscaped garden. The travel desk assists with sight-seeing and car rental service. Other services like laundry, room service and airport transportation are available at this property.The Bus Stand JK SRTC is located at a distance of 3 km and Leh Kushok Bakula Rimpochey Airport is 4 km away from the hotel. Moti Market (3 km) Leh Palace (4 km), Changspa (2 km) and Thiksey Monastery (18 km) are the famous tourist attractions from this property.Featuring free Wi-Fi connectivity and breakfast service, Sangto Green Guest House is located below Changspa Farm and at a distance of 3 km from the Shanti Stupa.This guest house in Leh has 2 floors and accommodates 6 well-furnished rooms. Each room is equipped with comfortable bed, seating area and an attached bathroom with hot and cold water facility.",
		city: "Leh",
		cleanPass: true,
		location: "Changspa",
		service: 1,
		couple: true,
		feeCancellation: false,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: true,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: false,
		resort: false,
		villa: false,
		guestHouse: false,
		BedAndBreakfast: true,
		yatraSmart: false,
		welcomeHeritageHotel: false,
	},
	{
		id: 9,
		name: "Hotel Shaolin Ladakh",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1556790087/Hotel/Leh/00083972/Overveiw_7xFxAd.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1556790087/Hotel/Leh/00083972/Overveiw_7xFxAd.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008082/Hotel/Leh/00083972/Room_View_uZ05kO.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008103/Hotel/Leh/00083972/Standard_Room_(1)_tTKjuE.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008186/Hotel/Leh/00083972/Deluxe_Room_(7)_sBfHld.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008228/Hotel/Leh/00083972/Deluxe_Room_(5)_GjEPrt.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008248/Hotel/Leh/00083972/Deluxe_Room_(1)_DQrQ82.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008283/Hotel/Leh/00083972/Washroom_(1)_ibx19U.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008298/Hotel/Leh/00083972/Washroom_(2)_v0YCdT.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490008421/Hotel/Leh/00083972/Standard_Room_(4)_3wUPFs.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1556789903/Hotel/Leh/00083972/bathroom_96yrxr.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1556789929/Hotel/Leh/00083972/Bedroom_RuFy5I.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1556789941/Hotel/Leh/00083972/Deluxe_(2)_SG6b8j.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1556789955/Hotel/Leh/00083972/Deluxe_L1BXs9.jpg",
		],
		rating: 2,
		price: 24000,
		sPrice: "24,000",
		otherRatingName: "Phenomenal Service",
		otherRating: 5.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"Sangto Green Guest has a landscaped garden. The travel desk assists with sight-seeing and car rental service. Other services like laundry, room service and airport transportation are available at this property.The Bus Stand JK SRTC is located at a distance of 3 km and Leh Kushok Bakula Rimpochey Airport is 4 km away from the hotel. Moti Market (3 km) Leh Palace (4 km), Changspa (2 km) and Thiksey Monastery (18 km) are the famous tourist attractions from this property.Featuring free Wi-Fi connectivity and breakfast service, Sangto Green Guest House is located below Changspa Farm and at a distance of 3 km from the Shanti Stupa.This guest house in Leh has 2 floors and accommodates 6 well-furnished rooms. Each room is equipped with comfortable bed, seating area and an attached bathroom with hot and cold water facility.",
		city: "Leh",
		cleanPass: true,
		location: "Old Road",
		service: 1,
		couple: false,
		feeCancellation: false,
		breakfast: true,
		wifi: true,
		airportTranspotation: false,
		laundry: true,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: false,
		resort: false,
		guestHouse: false,
		BedAndBreakfast: true,
		villa: false,
		yatraSmart: false,
		welcomeHeritageHotel: false,
	},
	{
		id: 10,
		name: "The Maitreya Ladakh",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683636/Hotel/Leh/00115912/Exterior_jMF4e7.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683636/Hotel/Leh/00115912/Exterior_jMF4e7.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683671/Hotel/Leh/00115912/1_2EFG0W.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683703/Hotel/Leh/00115912/10_tctZoy.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683714/Hotel/Leh/00115912/18_xOeAHh.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683748/Hotel/Leh/00115912/8_xK2Lkv.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683758/Hotel/Leh/00115912/9_K95L2w.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683787/Hotel/Leh/00115912/17_XiyJsO.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683798/Hotel/Leh/00115912/16_2imimX.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683823/Hotel/Leh/00115912/5_va756X.jpg",
		],
		rating: 2,
		price: 5500,
		sPrice: "5500",
		otherRatingName: "Wonderful  Location",
		otherRating: 4.5,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"Situated approximately 1 km away from Leh Palace, The Maitreya Ladakh is a budget accommodation in Leh offering breakfast service and Wi-Fi access to its guests. The Bus Stand JK SRTC is located 3 km away from the premises.A total of 24 well-kept and spacious rooms are available for accommodation. Some of the in-room amenities offered are wardrobe, television, separate sitting area, makeup mirror and attached bathroom with hot and cold running water facility.Apart from good accommodation in Leh, the property provides medical assistance and room service. Other facilities include travel counter, ATM, banquet hall and business center to name a few.Nearby points of interest to drop by includes Hall of Fame (7 km) and The Wheel of Life Ladakh (3 km). The Maitreya Ladakh is accessible from Leh Kushok Bakula Rinpoche Airport (6 km)",
		city: "Leh",
		cleanPass: true,
		location: "Skara",
		service: 1,
		couple: true,
		feeCancellation: false,
		breakfast: true,
		wifi: true,
		airportTranspotation: true,
		laundry: false,
		bar: true,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: true,
		resort: false,
		guestHouse: true,
		BedAndBreakfast: true,
		villa: false,
		yatraSmart: true,
		welcomeHeritageHotel: false,
	},
	{
		id: 11,
		name: "Hotel Skittsal",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683636/Hotel/Leh/00115912/Exterior_jMF4e7.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683636/Hotel/Leh/00115912/Exterior_jMF4e7.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683671/Hotel/Leh/00115912/1_2EFG0W.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683703/Hotel/Leh/00115912/10_tctZoy.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683714/Hotel/Leh/00115912/18_xOeAHh.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683748/Hotel/Leh/00115912/8_xK2Lkv.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683758/Hotel/Leh/00115912/9_K95L2w.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683787/Hotel/Leh/00115912/17_XiyJsO.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683798/Hotel/Leh/00115912/16_2imimX.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1518683823/Hotel/Leh/00115912/5_va756X.jpg",
		],
		rating: 4,
		price: 7500,
		sPrice: "5500",
		otherRatingName: "Wonderful  Location",
		otherRating: 4.5,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "4.5/5"],
		overView:
			"Situated approximately 1 km away from Leh Palace, The Maitreya Ladakh is a budget accommodation in Leh offering breakfast service and Wi-Fi access to its guests. The Bus Stand JK SRTC is located 3 km away from the premises.A total of 24 well-kept and spacious rooms are available for accommodation. Some of the in-room amenities offered are wardrobe, television, separate sitting area, makeup mirror and attached bathroom with hot and cold running water facility.Apart from good accommodation in Leh, the property provides medical assistance and room service. Other facilities include travel counter, ATM, banquet hall and business center to name a few.Nearby points of interest to drop by includes Hall of Fame (7 km) and The Wheel of Life Ladakh (3 km). The Maitreya Ladakh is accessible from Leh Kushok Bakula Rinpoche Airport (6 km)",
		city: "Leh",
		cleanPass: true,
		location: "Changspa",
		service: 1,
		couple: true,
		feeCancellation: false,
		breakfast: true,
		wifi: true,
		airportTranspotation: true,
		laundry: false,
		bar: true,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: true,
		resort: false,
		guestHouse: false,
		villa: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: true,
	},
	{
		id: 12,
		name: "Hotel Mandala",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v2531393204/Hotel/00002417/MD_5_xVcJJm.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v2531393204/Hotel/00002417/MD_5_xVcJJm.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1467540356/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Super%20Deluxe%20Room/Super_Deluxe_Room_mNKDoy.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1455356984/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Restaurant-1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1455356995/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Terrace-dinning.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1455356981/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Premium-room.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1455356989/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Side-view.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1455356985/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Room-interior.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1455356978/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Deluxe-room.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1455356992/Domestic%20Hotels/Hotels_Leh/Hotel%20Mandala/Suite-room.jpg",
		],
		rating: 2,
		price: 1820,
		sPrice: "1820",
		otherRatingName: "mpressive  Location",
		otherRating: 4.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "3.5/5"],
		overView:
			"Located in Sheynam village on the Fort Road, this hotel is 20 minutes walking distance from the main market area. The hotel offers quality service and modern facilities. There are comfortable rooms with hot shower and modern amenities. Authentic Ladakhi cuisine along with Chinese, Indian, and Continental fare is served to the guests. They can enjoy the beauty of the place by indulging in a sightseeing tour of the city. Adventurous activities include: White-water rafting and archery contest.Serving Indian, Chinese and continental delicacies the hotel proves to be a real gourmet's delight. The hotel also has a travel desk to cater to the travel needs of the guests. There are also cultural evenings organized on request for the entertainment of the guests.",
		city: "Leh",
		cleanPass: true,
		location: "Chulung",
		service: 0,
		couple: false,
		feeCancellation: false,
		breakfast: true,
		wifi: true,
		airportTranspotation: false,
		laundry: false,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: true,
		resort: false,
		guestHouse: false,
		villa: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: false,
	},
	{
		id: 13,
		name: "Hotel Caravan Centre",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v2531393204/Hotel/00002417/MD_5_xVcJJm.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1493979749/Hotel/Leh/00085957/Overview_Yw2XGW.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1493979826/Hotel/Leh/00085957/Corridor_aug4u5.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1493979836/Hotel/Leh/00085957/Bedroom_s5OXSh.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1524212932/Hotel/00085957/46C93B14-FBD3-4CF5-8546-7F0E77301B53_QGahWG.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1524213037/Hotel/00085957/6A984BF6-B6E9-4641-A1D4-847880E15020_XeSgw9.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1524213084/Hotel/00085957/07678803-0AA4-498D-B650-B8164ACA7AF5_eP2Emp.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1493979836/Hotel/Leh/00085957/Bedroom_s5OXSh.jpg",
		],
		rating: 3,
		price: 4600,
		sPrice: "5600",
		otherRatingName: "impressive Location",
		otherRating: 3.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "3.5/5"],
		overView:
			"Jan Palace Hotel is roughly located 0.5 km away from Jama Masjid and 4 km from Leh Kushok Bakula Rimpochee Airport. As a value added service, guests can avail of complimentary internet access, during their stay.Patrons are offered accommodation in 22 spacious rooms that are equipped with double bed, satellite television, telephone, coffee table with chairs and bathroom facility with hot water supply. Tour/travel assistance along with arrangement of cultural tours and sightseeing tours, laundry, doctor on call and power backup facility are a few of the facilities and services offered at Jan Palace Hotel. This hotel in Leh is inclusive of a front desk (limited-hours) and a secured parking space within its premises.Places worth a visit include Red Maitreya Temple (0.5 km), Guru Lhakhang (0.5 km) and Shanti Stupa (3 km). Leh Taxi Stand (0.5 km) and LBOC Ltd Leh Bus Stand (2 km) are a few of the travel hubs via which this hotel in Leh can be reached",
		city: "Leh",
		cleanPass: true,
		location: "Leh",
		service: 0,
		couple: false,
		feeCancellation: false,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: false,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: true,
		resort: false,
		guestHouse: false,
		BedAndBreakfast: false,
		villa: false,
		yatraSmart: false,
		welcomeHeritageHotel: false,
	},
	{
		id: 14,
		name: "Ule Ethnic Resort",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958930/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Overview.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958930/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Exterior-2.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958928/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Exterior-4.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958927/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Recpectiomn.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958927/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Wash-Room.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958928/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Library.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958926/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Exterior.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958930/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Bed-Room-1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1436958928/Domestic%20Hotels/Hotels_Leh/ULE%20ETHNIC%20RESORT/Room-View.jpg",
		],
		rating: 3,
		price: 4600,
		sPrice: "5600",
		otherRatingName: "impressive Location",
		otherRating: 3.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "3.5/5"],
		overView:
			"Jan Palace Hotel is roughly located 0.5 km away from Jama Masjid and 4 km from Leh Kushok Bakula Rimpochee Airport. As a value added service, guests can avail of complimentary internet access, during their stay.Patrons are offered accommodation in 22 spacious rooms that are equipped with double bed, satellite television, telephone, coffee table with chairs and bathroom facility with hot water supply. Tour/travel assistance along with arrangement of cultural tours and sightseeing tours, laundry, doctor on call and power backup facility are a few of the facilities and services offered at Jan Palace Hotel. This hotel in Leh is inclusive of a front desk (limited-hours) and a secured parking space within its premises.Places worth a visit include Red Maitreya Temple (0.5 km), Guru Lhakhang (0.5 km) and Shanti Stupa (3 km). Leh Taxi Stand (0.5 km) and LBOC Ltd Leh Bus Stand (2 km) are a few of the travel hubs via which this hotel in Leh can be reached",
		city: "Leh",
		cleanPass: true,
		location: "Leh",
		service: 0,
		couple: false,
		feeCancellation: false,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: true,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: true,
		resort: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: false,
		welcomeHeritageHotel: false,
		villa: true,
	},

	{
		id: 15,
		name: "The Ladakh Sarai",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424350584/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/NEWWING.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424350584/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/NEWWING.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490867521/Hotel/Leh/00000017/Bedroom_View_(2)_TOdWNx.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1491113004/Hotel/Leh/00000017/Dinning_Hall_T89Nr7.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743495/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/LOUNGEAREA.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743574/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/EXTERIORSITTING.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424434041/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/YURT.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424438072/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/Outerview.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743334/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/ROOM1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743516/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/WASHROOM.jpg",
		],
		rating: 4,
		price: 8400,
		sPrice: "8400",
		otherRatingName: "Phenomenal Service",
		otherRating: 4.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "3.5/5"],
		overView:
			"Jan Palace Hotel is roughly located 0.5 km away from Jama Masjid and 4 km from Leh Kushok Bakula Rimpochee Airport. As a value added service, guests can avail of complimentary internet access, during their stay.Patrons are offered accommodation in 22 spacious rooms that are equipped with double bed, satellite television, telephone, coffee table with chairs and bathroom facility with hot water supply. Tour/travel assistance along with arrangement of cultural tours and sightseeing tours, laundry, doctor on call and power backup facility are a few of the facilities and services offered at Jan Palace Hotel. This hotel in Leh is inclusive of a front desk (limited-hours) and a secured parking space within its premises.Places worth a visit include Red Maitreya Temple (0.5 km), Guru Lhakhang (0.5 km) and Shanti Stupa (3 km). Leh Taxi Stand (0.5 km) and LBOC Ltd Leh Bus Stand (2 km) are a few of the travel hubs via which this hotel in Leh can be reached",
		city: "Leh",
		cleanPass: true,
		location: "Leh",
		service: 3,
		couple: true,
		feeCancellation: true,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: true,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: false,
		resort: false,
		villa: true,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: true,
		welcomeHeritageHotel: true,
	},

	{
		id: 16,
		name: "Hotel OM Ladakh",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1453111570/Domestic%20Hotels/Hotels_Leh/Hotel%20OM%20Ladakh/Overview.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1453111570/Domestic%20Hotels/Hotels_Leh/Hotel%20OM%20Ladakh/Overview.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490867521/Hotel/Leh/00000017/Bedroom_View_(2)_TOdWNx.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1491113004/Hotel/Leh/00000017/Dinning_Hall_T89Nr7.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743495/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/LOUNGEAREA.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743574/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/EXTERIORSITTING.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424434041/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/YURT.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424438072/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/Outerview.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743334/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/ROOM1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743516/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/WASHROOM.jpg",
		],
		rating: 2,
		price: 3200,
		sPrice: "3200",
		otherRatingName: "Phenomenal Service",
		otherRating: 4.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "3.5/5"],
		overView:
			"Jan Palace Hotel is roughly located 0.5 km away from Jama Masjid and 4 km from Leh Kushok Bakula Rimpochee Airport. As a value added service, guests can avail of complimentary internet access, during their stay.Patrons are offered accommodation in 22 spacious rooms that are equipped with double bed, satellite television, telephone, coffee table with chairs and bathroom facility with hot water supply. Tour/travel assistance along with arrangement of cultural tours and sightseeing tours, laundry, doctor on call and power backup facility are a few of the facilities and services offered at Jan Palace Hotel. This hotel in Leh is inclusive of a front desk (limited-hours) and a secured parking space within its premises.Places worth a visit include Red Maitreya Temple (0.5 km), Guru Lhakhang (0.5 km) and Shanti Stupa (3 km). Leh Taxi Stand (0.5 km) and LBOC Ltd Leh Bus Stand (2 km) are a few of the travel hubs via which this hotel in Leh can be reached",
		city: "Leh",
		cleanPass: true,
		location: "Upper Tukcha Road",
		service: 3,
		couple: true,
		feeCancellation: true,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: true,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: true,
		resort: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: true,
		villa: false,
		welcomeHeritageHotel: true,
	},

	{
		id: 17,
		name: "Hotel OM Ladakh",
		headImage:
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1453111570/Domestic%20Hotels/Hotels_Leh/Hotel%20OM%20Ladakh/Overview.jpg",
		images: [
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1453111570/Domestic%20Hotels/Hotels_Leh/Hotel%20OM%20Ladakh/Overview.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1490867521/Hotel/Leh/00000017/Bedroom_View_(2)_TOdWNx.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1491113004/Hotel/Leh/00000017/Dinning_Hall_T89Nr7.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743495/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/LOUNGEAREA.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743574/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/EXTERIORSITTING.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424434041/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/YURT.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1424438072/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/Outerview.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743334/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/ROOM1.jpg",
			"https://imgcld.yatra.com/ytimages/image/upload/t_hotel_yatra_details_desktop/v1433743516/Domestic%20Hotels/Hotels_Leh/The%20Ladakh%20Sarai/WASHROOM.jpg",
		],
		rating: 2,
		price: 3200,
		sPrice: "3200",
		otherRatingName: "Phenomenal Service",
		otherRating: 4.0,
		tripAdvicerRating: 4.5,
		otherRatingName1: ["Wonderful Location", "Impressive Service"],
		ratingArray: ["4.5/5", "3.5/5"],
		overView:
			"Jan Palace Hotel is roughly located 0.5 km away from Jama Masjid and 4 km from Leh Kushok Bakula Rimpochee Airport. As a value added service, guests can avail of complimentary internet access, during their stay.Patrons are offered accommodation in 22 spacious rooms that are equipped with double bed, satellite television, telephone, coffee table with chairs and bathroom facility with hot water supply. Tour/travel assistance along with arrangement of cultural tours and sightseeing tours, laundry, doctor on call and power backup facility are a few of the facilities and services offered at Jan Palace Hotel. This hotel in Leh is inclusive of a front desk (limited-hours) and a secured parking space within its premises.Places worth a visit include Red Maitreya Temple (0.5 km), Guru Lhakhang (0.5 km) and Shanti Stupa (3 km). Leh Taxi Stand (0.5 km) and LBOC Ltd Leh Bus Stand (2 km) are a few of the travel hubs via which this hotel in Leh can be reached",
		city: "Leh",
		cleanPass: true,
		location: "Upper Tukcha Road",
		service: 3,
		couple: true,
		feeCancellation: true,
		breakfast: true,
		wifi: false,
		airportTranspotation: false,
		laundry: true,
		bar: false,
		children: true,
		swimmingPool: false,
		parking: false,
		hotles: true,
		resort: false,
		guestHouse: false,
		BedAndBreakfast: false,
		yatraSmart: true,
		villa: false,
		welcomeHeritageHotel: true,
	},
];
